DROP TABLE `users`;

CREATE TABLE `users` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `first_name` varchar(255) default NULL,
  `last_name` varchar(255) default NULL,
  `balance` mediumint default NULL,
  `email` varchar(255) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Ray","Richards",39669,"ligula.tortor@Etiam.edu"),("Amaya","Emerson",59332,"nibh.Aliquam.ornare@Aliquamauctorvelit.co.uk"),("Hyatt","Guthrie",31601,"quis.pede@Quisquevarius.edu"),("Iona","Salas",33985,"Duis@insodaleselit.edu"),("Wendy","Brennan",78264,"augue.id.ante@Loremipsumdolor.org"),("Lael","Stone",96396,"a@nonlobortis.org"),("Leonard","Moses",35230,"iaculis.nec.eleifend@Quisqueornare.net"),("Julie","Vaughn",47863,"porta.elit.a@at.org"),("Ursa","Beach",27294,"volutpat.Nulla@Nullam.ca"),("Susan","Rosario",67778,"Fusce.feugiat@dignissimpharetra.ca");
INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Idona","Benton",24412,"Mauris.magna.Duis@lacuspede.org"),("Amaya","Macdonald",20283,"ipsum.dolor@ultrices.org"),("Winter","Walsh",47960,"cursus.vestibulum@arcuet.ca"),("Ivor","Rush",79279,"quam.Curabitur.vel@sagittissemperNam.co.uk"),("Casey","Jones",50161,"ac@nequepellentesquemassa.edu"),("Macaulay","Cole",71362,"risus.Nunc.ac@CuraeDonectincidunt.ca"),("Clementine","Wallace",25371,"Sed.et@Fuscefeugiat.ca"),("Stephen","Levine",24111,"penatibus.et.magnis@facilisis.org"),("Ezekiel","Gates",24435,"tellus.Aenean.egestas@Aliquam.org"),("Addison","Dale",90568,"dui.Suspendisse@Nunccommodo.org");
INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Quincy","Castaneda",22833,"sodales@Fuscemilorem.com"),("Leah","Ruiz",44878,"lorem@lorem.org"),("Charde","Pittman",22045,"ac.mi.eleifend@diam.ca"),("Lane","Washington",29098,"non@scelerisque.org"),("Rhiannon","Salazar",50227,"eget.dictum.placerat@neque.co.uk"),("Violet","Barrera",62706,"cursus.diam.at@dignissimlacus.org"),("Kyla","Parker",64637,"lacus@variusultricesmauris.edu"),("Joelle","Clemons",42960,"hymenaeos@aliquamenimnec.org"),("Jessamine","Cote",44666,"Cras.dictum@Morbivehicula.co.uk"),("Naomi","Hunter",53292,"cursus@estNunc.net");
INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Bert","Bonner",53168,"pellentesque.tellus.sem@tempus.net"),("Kirk","Price",61801,"ipsum.sodales@nibh.net"),("Camilla","Avila",34749,"nibh.Donec.est@Maecenasmalesuada.net"),("Serina","Larsen",40590,"leo.Vivamus@eleifend.com"),("Anika","Dennis",20351,"Maecenas.mi@interdumCurabitur.ca"),("Moana","Elliott",12016,"Donec@ultricesDuisvolutpat.net"),("Arden","Gonzales",60412,"orci.luctus@enimSednulla.ca"),("Uriel","Woods",13565,"ullamcorper.Duis.at@congueInscelerisque.org"),("Caldwell","Lyons",54105,"mi.Aliquam.gravida@rhoncus.net"),("Desiree","Brady",53863,"lobortis.Class@nec.net");
INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Naida","Espinoza",60082,"sagittis.felis.Donec@lobortis.com"),("Adena","Young",80503,"odio.auctor.vitae@Nuncullamcorpervelit.net"),("Tyler","Manning",21653,"condimentum@disparturientmontes.co.uk"),("Kenyon","Small",29241,"quam.a.felis@orci.org"),("Lesley","Mcknight",10011,"tortor.nibh@malesuadavel.edu"),("Acton","Huffman",45866,"arcu.Vivamus.sit@Nullamvitae.co.uk"),("Arsenio","Pennington",97193,"ipsum.sodales@Sedauctorodio.com"),("Orli","Hamilton",56563,"enim@mollisdui.ca"),("Dale","Boyle",73583,"lectus.pede.ultrices@arcuCurabiturut.ca"),("Bert","Baldwin",38377,"lorem@liberoMorbiaccumsan.com");
INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Emi","Parsons",77771,"orci.quis.lectus@augue.co.uk"),("Austin","Nixon",33868,"tellus.lorem.eu@Cras.com"),("Shea","Bush",59628,"nulla@sociosqu.co.uk"),("Christopher","Hale",61834,"faucibus.orci.luctus@natoquepenatibus.ca"),("Brock","Emerson",56658,"vestibulum@ante.ca"),("Rebecca","Hardin",64658,"pretium.neque.Morbi@cursusdiam.edu"),("Giselle","Terry",84899,"eu@nec.org"),("Tanner","Freeman",44452,"blandit.at.nisi@acarcuNunc.ca"),("Rigel","Price",42630,"aliquet.Phasellus.fermentum@enimsitamet.net"),("Allegra","Willis",60482,"risus.Donec@enim.net");
INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Glenna","Ewing",52812,"eu@eu.co.uk"),("Cyrus","Luna",66794,"Sed@etlacinia.org"),("Phillip","Becker",32042,"cubilia.Curae.Donec@adipiscing.net"),("Olga","Hamilton",90770,"tincidunt.orci.quis@parturientmontes.net"),("Emily","Osborn",47619,"blandit.congue@atlacus.co.uk"),("Joelle","Sharp",94536,"natoque.penatibus@utsemNulla.co.uk"),("Tanek","Russo",18940,"lobortis.mauris.Suspendisse@Aliquam.ca"),("Aline","Cantrell",70519,"id@ipsumDonecsollicitudin.net"),("Peter","Huff",39255,"libero@non.org"),("Kirsten","Strickland",42402,"amet.orci.Ut@turpis.co.uk");
INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Caesar","Mccoy",98724,"mi.eleifend.egestas@nisi.ca"),("Clark","Robbins",78233,"mollis.non.cursus@acfermentumvel.org"),("Aristotle","Erickson",30928,"mi.eleifend.egestas@Pellentesqueutipsum.co.uk"),("Griffin","Price",67189,"magna.Sed.eu@vitaesodalesnisi.edu"),("Melvin","Bender",22180,"Mauris@Sed.co.uk"),("Barrett","Baker",29575,"tincidunt@purusac.edu"),("Macon","Houston",48214,"ullamcorper@odioauctorvitae.ca"),("Ali","Mueller",56758,"diam.nunc.ullamcorper@nibhdolor.edu"),("Jasper","Mccullough",84141,"luctus.et@Maurisvelturpis.com"),("Bianca","Mccoy",39743,"sit.amet@semmagna.net");
INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Cruz","Wilson",80801,"arcu.iaculis.enim@egestas.edu"),("Kirestin","Moody",77072,"non.dui.nec@feugiatnon.com"),("Amanda","Sears",39306,"ligula.Aliquam@Nullaeuneque.edu"),("Harper","Rivas",88313,"gravida.Aliquam@sed.co.uk"),("Iliana","Stokes",83333,"sed.pede@nequeNullam.net"),("Castor","Bryant",64009,"elementum.dui@felis.edu"),("Sean","Curry",82916,"malesuada.fames.ac@aliquameros.net"),("Freya","Mendoza",74961,"tristique.pharetra@id.co.uk"),("John","Morrison",30865,"faucibus.id@ligulaNullamfeugiat.org"),("Wesley","Garcia",82581,"arcu.imperdiet@ipsum.ca");
INSERT INTO `users` (`first_name`,`last_name`,`balance`,`email`) VALUES ("Alvin","Abbott",79913,"non@anteipsumprimis.co.uk"),("Quinlan","Browning",30730,"egestas@disparturientmontes.edu"),("Signe","Nguyen",98502,"ac@massaVestibulumaccumsan.com"),("Tanisha","Harris",15156,"Donec@atortorNunc.co.uk"),("Tanek","Turner",57864,"dis.parturient@cubiliaCuraePhasellus.net"),("Jaquelyn","Stephenson",32687,"metus@eratnequenon.co.uk"),("Jasper","Fry",99543,"consectetuer.cursus.et@nostraper.com"),("Dustin","Nunez",89520,"Integer@ametdiam.co.uk"),("Oren","Ayala",62953,"erat@facilisis.net"),("Quynn","Merritt",39137,"a.odio.semper@atlacusQuisque.edu");




