import Head from 'next/head';
import styles from '../styles/home.module.scss';
import { useState } from 'react';
import Link from 'next/link';

export default function Home() {
	const [redirect, setRedirect] = useState(false);
	return (
		<div className={styles.container}>
			<Head>
				<title>Basic Banking System</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/money-bag.png' />
			</Head>

			<div className={styles.content}>
				<h1>Basic Banking system</h1>
				<div onClick={() => setRedirect(true)}>
					<Link href='/users'>
						<a> &#12297;&#12297;&#12297;</a>
					</Link>
				</div>
			</div>
		</div>
	);
}
