import Head from 'next/head';

export default function Home({ users }) {
	return (
		<div>
			<Head>
				<title>Basic Banking System</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Basic Banking system</h1>
		</div>
	);
}
